### ISSUE TITLE
Maintaining fragment state when added to the back stack

### ISSUE THREAD

**Issue by Pirat4e** [Pirat4e/KinoNewApplication#1]
Everytime Im switching between fragments, its making new requests. I tried changing the request code' [place] (https://github.com/Pirat4e/KinoNewApplication/blob/master/app/src/main/java/com/empire/kinonewapplication/RepertoireTab.java#L45) inside onCreate(before onCreateView) but it did not work. Can i moderate the code to maintain the fragment state when its added to the bs? @inmyth

**Comment by inmyth** [comment]
You need to see this image:
http://stackoverflow.com/questions/17180225/android-end-fragment-activity
If you put add a request in onActivityCreated then it will be called when you switch between fragments. If you want to do request once then put it above. It is important to know that the fragment's layout is only available after onCreateView so you cannot initiate views like listview before this method. Maybe something like
````java

@Override
void onAttach(){
adapter = new KinoAdapter(getActivity(), R.layout.list_item_view);
StringRequest movieReq = new StringRequest(URL,
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response) {
                        Log.d(TAG, response.toString());
                        Wrap wrap = new Gson().fromJson(response, Wrap.class);
                        for (Post post : wrap.getPosts()) {
                            adapter.add(post);
                        }
                        adapter.notifyDataSetChanged();
                    }

                }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {
                VolleyLog.d(TAG, "Error: " + error.getMessage());
            }
        });
AppController.getInstance().addToRequestQueue(movieReq);
}

@Override
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
   View view = inflater.inflate(R.layout.repertoire_layout, container, false);
   listView = (ListView) view.findViewById(android.R.id.list);
   listView.setAdapter(adapter);
   return view;
}
````
Do not mix views from Activity with views from Fragment. This is wrong: 
````java
listView = (ListView) mActivity.findViewById(android.R.id.list);
````

**Comment by Pirat4e** [comment]
Thanks for the correction, I was trying the long way around. All the examples out there are showing a more complicated way.
